title: Luos Robotics documentation
logo: /assets/img/logo.png
description: Luos Robotics documentation
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
permalink: /module/:title
kramdown:
    auto_ids: true